### ISSUE TITLE
cannot run data preprocessing

### ISSUE THREAD

**Issue by wenbozhangjs** [devanshg27/cm_translatify#1]
Hello,

Thanks for sharing your working through Github! I'm trying to do the data preprocessing for the classification part. I directly use you scripts to finish preprocessing and meet some problems.

I'm following the order of:
(1) classification/datasets/download_data.sh
(2) classification/datasets/Data/Preprocess_Scripts/preprocess_sent_en_hi_2.py
(3) classification/datasets/Data/Preprocess_Scripts/to_translate_sent.py
(4) classification/datasets/Data/Preprocess_Scripts/translate_mbart.sh,
(5) classification/datasets/Data/Preprocess_Scripts/after_translate_sent.py

I finish step-1 and step-2. Right now, I cannot finish step-3 since you use the text file "sent_to_translate.txt" (Line 7 of to_translate_sent.py). Could you please add this file to this repository or just update this python file to let me know what is this file?

I also have a question in step-3. What's the correct path for line 18 (path for data), line 19(path for DATADIR),  line23(basedir) of translate_mbart.sh (i don't find correct path in the classification part)?  

I'm trying to cite your paper as a baseline in my draft. It would be great if you could update these scripts to make the whole preprocessing step runs smoothly.  However, I know that you may not have enough time to update the whole preprocessing part right now. If so, I could do some attempts after receiving your response.  Really appreciate your help!

**Comment by devanshg27** [comment]
Hello,

`sent_to_translate.txt` is the output file of the 3rd step. You can change the output path, but the same file path should be given as the input file in step 4.

These are the variables to be set in translate_mbart.sh:

- `INPUT_FILE` - Set this to be the same as the file path in line 7 of to_translate_sent.py.
- `OUTPUT_FILE` - Set this to be the same as the file path in line 7 of after_translate_sent.py.
- Replace `/home/devanshg27/delete/temp_dir/` everywhere in the file to a directory where the model can store temporary data.
- `BASEDIR` should be set to the best code-mixed -> English translation model checkpoint. I can't seem to find the trained checkpoint, so you'll have to train the model again. All the intermediate and final outputs are already uploaded on github in the Data directory.

Let me know if you have any more questions.

**Comment by wenbozhangjs** [comment]
Hello,

Thanks for your clarification. Right now, I finish step-3 and move to step-4(translate_mbart.sh). May I know how can I modify the line 49 (--path $2)? What's the meaning of this path?

Thank you!

**Comment by devanshg27** [comment]
Hello, the path argument should be set to the path of the best model checkpoint (.pt file) after fine tuning mBART.

**Comment by wenbozhangjs** [comment]
Thank you so much for the clarification. I could finish all the steps of preprocessing now
